name: Deploy when pushin
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Deploy code
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_port: ${{ secrets.REMOTE_PORT }}
          source: ./
          dest: /var/www/html/SunnyBenji